# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iOQUj5ufwXIO2GbeUM7a1J4xgYEje_4x
"""

def Compute_dist(l1):
  d1 = {}
  for i in l1:
    d1[i] = l1.count(i)
  return d1


if __name__ == "__main__":
    list1 =list(map(int,input().split()))
    print(Compute_dist(list1))